### ISSUE TITLE
Swift-only version?

### ISSUE THREAD

**Issue by warpdesign** [hotpaw2/auv3test5#3]
Just stumbled upon your code from [here](https://forums.developer.apple.com/thread/22530): thank you!

I was wondering if it would be possible to have the Objective-C part rewritten into Swift.

Since my playback routines (and the data that will hold the sound samples) will be in Swift I'm not sure how I could do that while keeping the unit's code into Objective-C.

**Comment by hotpaw2** [comment]
On Jul 17, 2019, at 1:50 AM, Nicolas Ramz <notifications@github.com> wrote:
> 
> I was wondering if it would be possible to have the Objective-C part rewritten into Swift.

The Objective C portion of the Audio Unit sample on GitHub is really coded in plain C code.  The reason is because, in Apple’s 2017 WWDC session 501, titled “What’s New in Audio”, there is this statement: "it is not safe to use Objective-C or Swift runtime from a real-time context”.  And an Audio Unit callback is run in an audio real-time context.  

If you want to use Swift in the real-time audio context, I recommend using it only to call memcpy (or equivalent) to copy audio data (perhaps pre-generated by Swift) into or out of pre-allocated buffers.  The sample Swift code and audio callback will also need to be updated to include memory barrier, store release, and load acquire memory synchronization primitives to prevent data read/writes from being reordered.

**Comment by warpdesign** [comment]
Thank for the details.

I did a quick and dirty (I'm not very familiar with Objective-C and am also new to Swift) port of your AudioUnit in Swift and it appears to be working quite well: https://github.com/warpdesign/modplayer-ios
